language: python
python: 2.7.13
sudo: false
cache:
  pip: true
  directories:
    - eggs
env:
  - PLONE_VERSION=5.1.x
before_install:
  - mkdir -p $HOME/buildout-cache/{eggs,downloads}
  - pip install -r requirements.txt
install:
  - sed -ie "s#plone-x.x.x.cfg#plone-$PLONE_VERSION.cfg#" buildout.cfg
  - buildout -N -t 3
script:
  - bin/code-analysis
  - bin/test
after_success:
  - pip install coveralls
  - coveralls

notifications:
  email:
    - sviluppoplone@redturtle.it
