language: python
python: 2.7
sudo: false
cache:
  pip: true
  directories:
    - eggs
env:
  matrix:
    - PLONE_VERSION=5.1.x
    - PLONE_VERSION=5.0.x
before_install:
  - mkdir -p $HOME/buildout-cache/{eggs,downloads}
  - pip install -r requirements.txt
install:
  - sed -ie "s#plone-x.x.x.cfg#plone-$PLONE_VERSION.cfg#" travis.cfg
  - buildout -Nt 3 -c travis.cfg
script:
  - bin/code-analysis
  - bin/test
after_success:
  - pip install coveralls
  - coveralls

notifications:
  email:
    - sviluppoplone@redturtle.it
